/**
 * export-source.ts
 *
 * Client-side utility that fetches every source file via the Next.js static
 * export and packages them into a downloadable ZIP using JSZip.
 *
 * Because Next.js static export serves files from /out, we cannot read the
 * filesystem at runtime. Instead, we ship the source as a pre-encoded JSON
 * manifest at build time (generated by the export-manifest route), OR — for
 * the simpler zero-config path — we link directly to the GitHub repository
 * archive which is always available for public repos.
 *
 * This module exposes two strategies:
 *  1. downloadFromGitHub()  — opens the GitHub archive URL in a new tab.
 *     Works for any public fork with zero configuration.
 *  2. downloadEmbeddedZip() — packages the embedded source manifest into a
 *     ZIP and triggers a browser download. Works fully offline / on any host.
 */

import JSZip from 'jszip'

const GITHUB_REPO = 'https://github.com/fantasticasd/v0-readme-visualizer'
const GITHUB_ARCHIVE = `${GITHUB_REPO}/archive/refs/heads/main.zip`

/**
 * Open the GitHub repository ZIP archive in a new tab.
 * Requires the repository to be public.
 */
export function downloadFromGitHub(): void {
  window.open(GITHUB_ARCHIVE, '_blank', 'noopener,noreferrer')
}

/**
 * Source files embedded at build time via next/dynamic import of the manifest.
 * Each entry is { path: string; content: string }.
 */
export type SourceFile = { path: string; content: string }

/**
 * Build a ZIP from an array of SourceFile entries and trigger a browser
 * download. Falls back gracefully if JSZip fails to load.
 */
export async function downloadEmbeddedZip(
  files: SourceFile[],
  zipName = 'readme-visualizer-source.zip',
): Promise<void> {
  const zip = new JSZip()
  const root = zip.folder('readme-visualizer') as JSZip

  for (const { path, content } of files) {
    root.file(path, content)
  }

  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  })

  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = zipName
  a.click()
  URL.revokeObjectURL(url)
}

/**
 * Fetches a list of known static text files from the deployed origin and
 * packages them into a ZIP. Works when the app is served over HTTP/S.
 * On file:// origins or when a file 404s the entry is skipped silently.
 */
export async function downloadDeployedZip(
  paths: string[],
  zipName = 'readme-visualizer-source.zip',
): Promise<void> {
  const zip = new JSZip()
  const root = zip.folder('readme-visualizer') as JSZip

  await Promise.all(
    paths.map(async (p) => {
      try {
        const res = await fetch(p)
        if (!res.ok) return
        const text = await res.text()
        // Strip leading slash for the ZIP path
        root.file(p.replace(/^\//, ''), text)
      } catch {
        // Skip files that cannot be fetched (e.g. file:// origin)
      }
    }),
  )

  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  })

  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = zipName
  a.click()
  URL.revokeObjectURL(url)
}
